name: CI

on:
  push:
    branches: [ master ]
    paths-ignore: ["**.md"]
  schedule:
    - cron: '0 0 12,26 * *' # roughly every two weeks to run on new Ruby versions
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.2
          - 3.3
          - ruby-head
        gemfile:
          # These are located in the gemfiles/ folder
          - rails71
          - rails72
          - rails71_boc
          - rails72_boc
          - rack
          - rack_boc
        exclude:
          - { ruby: 3.2,            gemfile: rails71 }
          - { ruby: 3.2,            gemfile: rails71_boc }
          - { ruby: 3.3,            gemfile: rails72 }
          - { ruby: 3.3,            gemfile: rails72_boc }
          - { ruby: ruby-head,        gemfile: rails42 }
          - { ruby: ruby-head,        gemfile: rails42_boc }

    steps:

    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: gemfiles/vendor/bundle
        key: v3-${{ runner.os }}-branch-${{ github.ref }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}-${{ hashFiles(format('gemfiles/{0}.gemfile', matrix.gemfile)) }}
        restore-keys: |
          v3-${{ runner.os }}-branch-${{ github.ref }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}
          v3-${{ runner.os }}-branch-master-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    - name: RSpec
      run: bundle exec rspec -f doc --color
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
